# Generated by Django 4.0 on 2021-12-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_photos_petphoto_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petphoto",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="api.pet",
            ),
        ),
    ]
