name: Testing Flow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip && pip install poetry==1.1.11
        poetry export -f requirements.txt --output requirements.txt
        pip install -r requirements.txt
        
    - name: Lint with flake8
      run: flake8 .

    - name: Run Django Migrations
      run: |
        python manage.py migrate
        
    - name: Django Testing project
      run: |
        pytest -c pytest.ini
